// compat/angular/src/primeng/slider.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { SliderModule } from 'primeng/slider';

@Component({
  standalone: true,
  imports: [FormsModule, SliderModule],
  template: `
    <p-slider [min]="0" [max]="100" [(ngModel)]="value"></p-slider>
    <div aria-label="result">{{ value }}</div>
  `,
})
export class PrimeNgSliderFixture {
  value = 20;
}

// compat/react/src/mui/slider.tsx
import { Slider } from '@mui/material';
import { useState } from 'react';

export function MuiSlider(props: any) {
  const [value, setValue] = useState(20);
  return (
    <div>
      <Slider aria-label="slider" min={0} max={100} onChange={(_, newValue) => setValue(newValue)} {...props} />
      <div aria-label="result">{value}</div>
    </div>
  );
}
