// compat/react/src/mui/slider.tsx
import { Slider } from '@mui/material';
import { useState } from 'react';

export function MuiSlider(props: any) {
  const [value, setValue] = useState(20);
  return (
    <div>
      <Slider aria-label="slider" min={0} max={100} onChange={(_, newValue) => setValue(newValue)} {...props} />
      <div aria-label="result">{value}</div>
    </div>
  );
}

// compat/angular/src/angular-material/slider.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatSliderModule } from '@angular/material/slider';

@Component({
  standalone: true,
  imports: [MatSliderModule, FormsModule],
  template: `
    <mat-slider min="0" max="100" aria-label="slider">
      <input matSliderThumb [(ngModel)]="value" />
    </mat-slider>
    <div aria-label="result">{{ value }}</div>
  `,
})
export class MatSliderFixture {
  value = 20;
}
