// compat/react/src/radix/slider.tsx
import * as Slider from '@radix-ui/react-slider';
import { useState } from 'react';

export function RadixSlider() {
  const [value, setValue] = useState([50]);
  return (
    <div>
      <Slider.Root aria-label="volume" min={0} max={100} value={value} onValueChange={setValue}>
        <Slider.Track>
          <Slider.Range />
        </Slider.Track>
        <Slider.Thumb aria-label="volume" />
      </Slider.Root>
      <div aria-label="result">{value[0]}</div>
    </div>
  );
}

// compat/angular/src/taiga-ui/slider.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { TuiSlider } from '@taiga-ui/core/components/slider';

@Component({
  standalone: true,
  imports: [FormsModule, TuiSlider],
  template: `
    <input type="range" tuiSlider min="0" max="100" step="1" [(ngModel)]="value" />
    <div aria-label="result">{{ value }}</div>
  `,
})
export class TaigaSliderFixture {
  value = 20;
}
